import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


export default function RootLayout(
  {children}: Readonly<{children : React.ReactNode}>
){
  return(
    <html className='dark'>
      <body className={inter.className}>
        <div className="relative w-full flex justify-center items-center">
          <Navbar className="border  rounded-3xl"/>
        </div>
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  )
}